"""third_migration

Revision ID: 90ad2953e01b
Revises: 9683b674d1a7
Create Date: 2025-03-30 11:45:23.047226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ad2953e01b'
down_revision: Union[str, None] = '9683b674d1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasports',
    sa.Column('id_passport', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_passport')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pasports')
    # ### end Alembic commands ###
