"""second_migration

Revision ID: 9683b674d1a7
Revises: e7f56e994dfc
Create Date: 2025-03-29 19:12:23.781220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9683b674d1a7'
down_revision: Union[str, None] = 'e7f56e994dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply', sa.Column('test', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supply', 'test')
    # ### end Alembic commands ###
